---
title: "Template Tabular Analysis"
subtitle: "IPHRA_Yemen"
date: today

format: 
  html:
    grid:
      sidebar-width: 250px
      body-width: 1000px
    title-block-banner: true
    theme: scss/reach_theme.scss

params: 
    results_table_path: "../outputs/03 - analysis/all_analysis.rds"
    daf: "../inputs/daf_example (1).xlsx"
---
```{r}
#| include: false

library(tidyverse)
results_table <- readRDS(params$results_table_path)
daf <- readxl::read_excel(params$daf)

section_info <- daf %>% 
  select(section, analysis_var, label) %>% 
  filter(!duplicated(analysis_var)) %>% 
  mutate(section = as_factor(section))

all_results <- results_table %>% 
  map(\(x) x[["results_table"]]) %>% 
  bind_rows()

all_results <- all_results %>% 
  left_join(section_info)

all_results <- all_results |>
  select(-analysis_key) |>
  mutate(across(any_of(c("stat","stat_low","stat_upp")), ~round(.x, digits =2)))

names_sections_list <- all_results |>
  group_by(section) |>
  group_keys()

sections_results_table_list <- all_results |>
  group_by(section) |>
  group_split() |>
  set_names(names_sections_list$section)


names_list <- sections_results_table_list |>
  map(\(x)  x |> group_by(label,analysis_var,group_var) |> group_keys()
)

results_table_list <- map2(sections_results_table_list, 
                           names_list,
                           \(x,y) x |>
                             group_by(label,analysis_var,group_var) |>
                             group_split() |>
                             map(~select(.x,-analysis_type, -section, -label)) |>
                             set_names(y[["label"]])
)
  
```
```{r}
#| include: false
results_table_list %>%
  map(\(x) x |> map(DT::datatable)) |> 
  htmltools::tagList()

```

::: {.panel-tabset}

## Introduction

```{r}
#| echo: false
#| results: asis
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "What is this tool?"))
  cat('\nThe IPHRA Tabular Analysis is an analytical platform that presents a multitude of quantitative data tables. It encompasses a wide range of indicators collected through the IPHRA assessment process, empowering users to examine and interpret complex datasets effectively. This tool is structured to support understanding the distribution of your data and support you writing your factsheets/outputs/reports, and create other visualizations.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "What is in this tool?"))
   cat('\nWithin this tool, users will find a wealth of information organized into distinct categories, each pertaining to critical aspects of humanitarian analysis:')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Household (HH) Demographics"))
  cat('\nExamine the composition and distribution of populations within households.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Individual (IND) Demographics"))
  cat('\nDelve into detailed demographic breakdowns at the individual level.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Healthcare"))
  cat('\nAccess data on healthcare availability, utilization, and specific health outcomes within communities on individual and household level.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "WASH"))
  cat('\nUnderstand the access and quality of WASH facilities and practices.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Shelter"))
  cat('\nReview information on the types and adequacy of shelter among the assessed population.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Child Nutrition"))
  cat('\nGet insights into the nutritional status and risk factors affecting children.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Women"))
  cat('\nFocus on gender-specific data that highlights the situation of women in the context of healthcare, nutrition, and risk.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Death"))
  cat('\nAnalyze rates and causes of death to gauge the health environment')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Food Security and Livelihood (FSL)"))
  cat('\nExplore data on food availability, accessibility, and livelihood resources.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Mortality"))
  cat('\nAssess overall mortality rates to understand broader health trends.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "MUAC/Nutrition"))
  cat('\nEvaluate nutritional status indicators, such as MUAC measurements, to determine the prevalence of malnutrition.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "What else to know?"))
  cat('\nAs you saw in the output folder, you will have another excel file outputed from the analysis script. The Excel file includes 4 sheets. The first 2 are all the tables that you see in the different sections of this HTML output. You can navigate to respective tables through the first sheet "Table of Contents". The third sheet is nothing more than just the tables shown in the MUAC/Nutrition tab. The fourth tab is showing the Nutrition indices table disaggregated by sex and age. Please be aware of the footnote indication on the usage of the final percentages.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "Feedback"))
  cat('\nFeedback on improvements to this product can be done through reaching out to:\n\n-abraham.azar@impact-initiatives.org \n\n -impact.geneva.phu@impact-initiatives.org')

```

```{r}
#| results: asis
#| echo: false

for(i in names_sections_list$section) {
  cat(paste("\n##", i, "\n\n"))
  for(j in names(results_table_list[[i]])) {
  cat(paste("\n###", j, "\n\n"))
  print(htmltools::tagList(DT::datatable(results_table_list[[i]][[j]],
                                         options = list(scrollX  = TRUE))))}
}
```

:::